profilemanagement/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using ProfileManagement.Data;
using Microsoft.AspNetCore.Identity;
using ProfileManagement.Models;

namespace ProfileManagement.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public DashboardController(UserManager<ApplicationUser> userManager,ApplicationDbContext context)
        {
            _context = context;
            _userManager = userManager;
        }

    }
}

profilemanagement/Controllers/ProfileController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using ProfileManagement.Data;
using ProfileManagement.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Configuration;
using ProfileManagement.ViewModels;
using ProfileManagement.Interfaces;

namespace ProfileManagement.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUserService _userService;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IConfiguration _configuration;
        private string Root_Directory;
        public ProfileController(IConfiguration configuration, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager,IUserService userService)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _configuration = configuration;
            _userService = userService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public async  Task<IActionResult> IndividualProfileData(string id)
        {
            ProfileViewModel profileViewModel = new ProfileViewModel();
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                profileViewModel = await _userService.GetUserProfile(user.Id);
            }
            return View(profileViewModel);
        }
        public async Task<IActionResult> YourProfile()
        {
            var user = await _userManager.GetUserAsync(User);
            ProfileViewModel profile = new ProfileViewModel();
            if (user != null)
            {
                //profile.FullName = user.FullName ?? "";
                //profile.LastName = user.LastName ?? "";
                //profile.FirstName = user.FirstName ?? "";
                //profile.Email = user.Email ?? "";
                //profile.Mobile = user.PhoneNumber ?? "";
                //profile.CompanyName = user.CompanyName ?? "";
                //profile.OfficeAddress = user.OfficeAddress ?? "";
                //profile.CompanyWebsite = user.CompanyWebsite ?? "";
                //profile.OthersMemberEmail = user.OthersMemberEmail ?? "";
                //profile.ProfilePicture = user.ProfilePicture ?? "";
            }
            return View(profile);
        }
        //public async Task<IActionResult> SaveProfile(ProfileViewModel profile)
        //{
        //    try
        //    {
        //        var user = await _userManager.GetUserAsync(User);
        //        if (user != null)
        //        {
        //            if (!_context.Users.Where(x => x.PhoneNumber == profile.Mobile && x.Email != user.Email).Any())
        //            {
        //                user.PhoneNumber = profile.Mobile ?? "";
        //                //user.CompanyName = profile.CompanyName ?? "";
        //                //user.OfficeAddress = profile.OfficeAddress ?? "";
        //                //user.CompanyWebsite = profile.CompanyWebsite ?? "";
        //                //user.OthersMemberEmail = profile.OthersMemberEmail ?? "";

        //                _context.SaveChanges();
        //                if (!string.IsNullOrEmpty(profile.Password) && !string.IsNullOrEmpty(profile.NewPassword) && !string.IsNullOrEmpty(profile.ConfirmPassword) && profile.NewPassword.Equals(profile.ConfirmPassword))
        //                {
        //                    await _userManager.ChangePasswordAsync(user, profile.Password, profile.NewPassword);
        //                    await _signInManager.SignOutAsync();
        //                    return Json("pass");
        //                }

        //                return Json("success");
        //            }
        //            else
        //            {
        //                return Json("Phone number already used.");
        //            }
        //        }
        //        else
        //        {
        //            return Json("error");
        //        }
        //    }
        //    catch (Exception e)
        //    {
        //        return Json("error");
        //    }
        //}
        //[HttpPost]
        //public async Task<IActionResult> updatePassword(ProfileViewModel model)
        //{
        //    var user = _userManager.GetUserAsync(User).Result;
        //    if (!string.IsNullOrEmpty(model.Password) && (model.NewPassword == model.ConfirmPassword))
        //    {
        //        await _userManager.ChangePasswordAsync(user, model.Password, model.NewPassword);
        //        await _signInManager.SignOutAsync();
        //        return Json(true);
        //    }
        //    else
        //    {
        //        return Json(false);
        //    }
        //}
        //[HttpPost]
        //public async Task<IActionResult> UploadProfilePicture()
        //{
        //    var user = _userManager.GetUserAsync(User).Result;
        //    var file = Request.Form.Files[0];
        //    try
        //    {
        //        var uploadFolderUrl = $"{Root_Directory}/{user.Email}/ProfilePictures";
        //        if (file != null)
        //        {
        //            if (!Directory.Exists(uploadFolderUrl))
        //                Directory.CreateDirectory(uploadFolderUrl);
        //            var path = Path.Combine(uploadFolderUrl);
        //            using (var fileStream = new FileStream(Path.Combine(path, $"{user.Id}.jpg"), FileMode.Create))
        //            {

        //                await file.CopyToAsync(fileStream);
        //            }

        //        }
        //        var imageByte = Helper.GetImage($"{uploadFolderUrl}/{user.Id}.jpg");
        //        //user.ProfilePicture = $"{uploadFolderUrl}/{user.Id}.jpg";
        //        await _userManager.UpdateAsync(user);

        //        return Json(imageByte);
        //    }
        //    catch (Exception ex)
        //    {
        //        return Json(false);
        //    }

        //}
    }
}

profilemanagement/Controllers/UserController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using ProfileManagement.Models;
using Microsoft.AspNetCore.Identity;
using ProfileManagement.Interfaces;
using ProfileManagement.ViewModels;
using ProfileManagement.StaticData;
using ProfileManagement.Helpers;
using System.IO;
using Microsoft.Extensions.Configuration;
using Microsoft.EntityFrameworkCore.Internal;
using System.Linq;

namespace ProfileManagement.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IUserService _userService;
        private readonly IUserRepository _userRepository;
        private string Root_Directory;
        private readonly IConfiguration _configuration;
        private readonly IEducationRepository _educationRepository;
        private readonly IExperienceRepository _experienceRepository;
        
        public UserController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IUserService userService, IConfiguration configuration, IEducationRepository educationRepository, IExperienceRepository experienceRepository, IUserRepository userRepository)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _userService = userService;
            _userRepository = userRepository;
            _configuration = configuration;
            _educationRepository = educationRepository;
            _experienceRepository = experienceRepository;
            Root_Directory = _configuration.GetSection("AppSettings").GetSection("Root_Directory").Value;
        }

        public async Task<IActionResult> Index()
        {
            ProfileViewModel profileViewModel = new ProfileViewModel();
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                profileViewModel = await _userService.GetUserProfile(user.Id);
            }
            ///// check if profile data is emplty or not if empty then redirect to edit action
            if (profileViewModel.UserViewModel.Interests == null || profileViewModel.UserViewModel.PhoneNumber == null || profileViewModel.ExperienceInfos.Count <= 0)
            {
                return RedirectToAction("EditUser");
            }

            return View(profileViewModel);
            //return View();
        }
        public async Task<IActionResult> EditUser()
        {
            var user = await _userManager.GetUserAsync(User);
            UserProfileEditViewModel userViewModel = new UserProfileEditViewModel();
            if (user != null)
            {
                userViewModel = await _userService.GetUserProfileEditViewModel(user.Id);
                //userViewModel.DateforTest = Convert.ToDateTime(userViewModel.DateOfBirth);
                userViewModel.SelectedGender = (int)user.Gender;
                userViewModel.SelectedMaritalStatus = (int)user.MaritalStatus;
                userViewModel.DateOfBirth = Convert.ToDateTime(userViewModel.DateOfBirth).Date.ToString("yyyy-MM-dd");
            }

            return View(userViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> SaveProfile(UserProfileEditViewModel profile)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                if (user != null)
                {
                    //if (!ModelState.IsValid)
                    //{
                    //    //ModelState.AddModelError(nameof(profile), "please give valid data");
                    //    //return Json(new { error = true, success = false, message = "please give valid data" });
                    //    return RedirectToAction("EditUser");
                    //    // return RedirectToAction("EditUser");
                    //}
                    if (string.IsNullOrWhiteSpace(profile.FirstName) || string.IsNullOrWhiteSpace(profile.Designation) 
                        || string.IsNullOrWhiteSpace(profile.LastName) || string.IsNullOrWhiteSpace(profile.Interests)
                        || profile.SelectedGender == 0 || profile.SelectedMaritalStatus == 0)
                        return Json(new { error = true, success = false, message = "please give valid data" });

                    user.FirstName = profile.FirstName;
                    user.LastName = profile.LastName;
                    user.Gender = (Gender)profile.SelectedGender;
                    user.MaritalStatus = (MaritalStatus)profile.SelectedMaritalStatus;
                    user.DateOfBirth = Convert.ToDateTime(profile.DateOfBirth);
                    user.FullName = profile.FirstName + " " + profile.LastName;
                    user.Designation = profile.Designation;
                    user.Country = profile.Country;
                    user.City = profile.City;
                    user.Interests = profile.Interests;

                    await _userService.UpdateUser(user);


                    //return View("EditUser");
                    return Json(new { success = true, message = "save successfully" });
                    //if (!_context.Users.Where(x => x.PhoneNumber == profile.Mobile && x.Email != user.Email).Any())
                    //{
                    //user.PhoneNumber = profile.PhoneNumber ?? "";
                    //user.CompanyName = profile.CompanyName ?? "";
                    //user.OfficeAddress = profile.OfficeAddress ?? "";
                    //user.CompanyWebsite = profile.CompanyWebsite ?? "";
                    //user.OthersMemberEmail = profile.OthersMemberEmail ?? "";

                    //_context.SaveChanges();
                    //if (!string.IsNullOrEmpty(profile.Password) && !string.IsNullOrEmpty(profile.NewPassword) && !string.IsNullOrEmpty(profile.ConfirmPassword) && profile.NewPassword.Equals(profile.ConfirmPassword))
                    //{
                    //    await _userManager.ChangePasswordAsync(user, profile.Password, profile.NewPassword);
                    //    await _signInManager.SignOutAsync();
                    //    return Json("pass");
                    //}

                    //return RedirectToAction("Index");
                    //}
                    //else
                    //{
                    //    return Json("Phone number already used.");
                    //}
                }
                else
                {
                    //return Json("error");
                    return Json(new { error = true, success = false, message = "No user detected" });
                    //return RedirectToAction("EditUser");
                }
            }
            catch (Exception ex)
            {
                //return Json("error");
                return Json(new { error = true, success = false, message = ex.Message });
                //return RedirectToAction("EditUser");
            }
        }

        [HttpPost]
        public async Task<IActionResult> SaveContactInfoWithAjax(UserProfileEditViewModel profile)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                if (user != null)
                {
                    if (String.IsNullOrEmpty(profile.PhoneNumber) || String.IsNullOrEmpty(profile.Email))
                    {
                        return Json(new { error = true, success = false, message = "please give valid data" });
                        // return RedirectToAction("EditUser");
                    }
                    profile.UserId = user.Id;
                    // check for duplicate value
                    //var contactInfo = _userRepository.GetAllWithOutCurrentUser(user.Id);
                    var isDuplicate = CheckUserDuplicateContactInfo(profile);
                    if (isDuplicate)
                    {
                        return Json(new { error = true, success = false, message = "Data already exists!." });
                    }


                    // check this
                    user.PhoneNumber = profile.PhoneNumber;
                    user.Email = profile.Email;
                    user.Website = profile.Website;
                    user.Facebook = profile.Facebook;
                    user.Twitter = profile.Twitter;
                    await _userService.UpdateUser(user);
                    //return RedirectToAction("Index");
                    //return Json("success");
                    return Json(new { success = true, message = "save successfully" });
                }
                else
                {
                    return Json(new { success = false, message = "somthing went wrong" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }

        //[HttpPost]
        //public async Task<IActionResult> SaveContactInfo(UserProfileEditViewModel profile)
        //{
        //    try
        //    {
        //        var user = await _userManager.GetUserAsync(User);
        //        if (user != null)
        //        {
        //            user.PhoneNumber = profile.PhoneNumber;
        //            user.Email = profile.Email;
        //            user.Website = profile.Website;
        //            user.Facebook = profile.Facebook;
        //            user.Twitter = profile.Twitter;
        //            await _userService.UpdateUser(user);
        //            return RedirectToAction("Index");
        //            //return Json("success");
        //        }
        //        else
        //        {
        //            return Json("error");
        //        }
        //    }
        //    catch (Exception e)
        //    {

profilemanagement/Views/Shared/_BLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Profile</title>

    <environment include="Development,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/thumbnail-gallery.css"/>
        <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">
        <link rel="stylesheet" href="~/css/uptown.css"/>
        <link rel="stylesheet" href="~/css/cutoutwizApp.css"/>
        <link rel="stylesheet" href="~/css/hover-min.css"/>
        <link rel="stylesheet" href="~/lib/intl-tel-input/css/intlTelInput.css"/>

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/appScript.js"></script>
        <script src="~/lib/intl-tel-input/js/intlTelInput.min.js"></script>
       <script src="~/js/toastr.min.js"></script>

    </environment>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="AdminPanel" asp-action="Index" class="navbar-brand">ProfileManagement</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   
                    <li><a asp-area="" asp-controller="AdminPanel" asp-action="AdminFaq">Add/Update Faq</a></li>
                    <li><a href="/AdminPanel/AllPaymentsRecords">Payment</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content column twelve">
        <main style="margin-top:70px">
        @RenderBody()
        </main>
        <hr />
        <footer>
            <p>&copy; 2017 - ProfileManagement</p>
        </footer>
    </div>

    <environment include="Development,Production">

       
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>


    @RenderSection("Scripts", required: false)
</body>
</html>

profilemanagement/Views/Shared/_CutOutWiz.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - CutOutWiz</title>
    <environment include="Development,Production">
        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Shadows+Into+Light%7CLibre+Franklin:200,300,400,600,700" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/fontawesome.min.css" />
        <link rel="stylesheet" href="~/cutoutwiz/css/style.css" />
        <link rel="stylesheet" href="~/css/thisSite.css" />
        <link rel="stylesheet" href="~/lib/intl-tel-input/css/intlTelInput.css" />
        <link rel="stylesheet" href="~/css/hover-min.css" />
        <link rel="stylesheet" href="~/lib/jquery-modal/jquery.modal.css" />
        <link rel="stylesheet" href="~/lib/fakeLoader/fakeLoader.css"/>
        <script src="~/lib/jquery/dist/jquery.js"></script>

        <script src="~/lib/jquery-circle-progress/dist/circle-progress.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/jquery.toaster.js"></script>
        <script src="~/lib/jquery-modal/jquery.modal.min.js"></script>

    </environment>
</head>
<body style="width:100%!important;overflow-x:hidden;overflow-y:scroll">
    <div id="fakeLoader"></div>
    <div class="text-center page">
        <header class="page-header">
            <!-- RD Navbar-->
            <div class="rd-navbar-wrap" style="height: 142px;">
                <nav style="background:#333333;padding-bottom:0!important" class="rd-navbar rd-navbar-default rd-navbar-original rd-navbar-static" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fullwidth" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static" data-lg-device-layout="rd-navbar-static" data-md-stick-up-offset="300px" data-lg-stick-up-offset="1px" data-stick-up="true" data-sm-stick-up="true" data-md-stick-up="true" data-lg-stick-up="true">
                    <div class="rd-navbar-inner">
                        <!-- RD Navbar Panel-->
                        <div class="rd-navbar-panel">
                            <!-- RD Navbar Toggle-->
                            <button class="rd-navbar-toggle toggle-original" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                            <!-- RD Navbar Brand-->
                            <div class="rd-navbar-brand">
                                <a class="brand-name" href="/Upload">
                                    <img src="~/cutoutwiz/images/logo.png" width="90px" height="90px" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="rd-navbar-aside-right">
                            <div class="rd-navbar-nav-wrap toggle-original-elements">
                                <!-- RD Navbar Nav-->
                                <ul class="rd-navbar-nav" style="color:aqua!important">
                                    <li><a asp-area="" asp-controller="Upload" asp-action="UploadPhoto">Upload</a></li>
                                    @*<li><a asp-area="" asp-controller="Dashboard" asp-action="PhotoGallery">Photo Gallery</a></li>*@
                                    <li><a asp-area="" asp-controller="Completion" asp-action="Index">Completed Images</a></li>
                                    <li><a asp-area="" asp-controller="Profile" asp-action="YourProfile">Profile</a></li>
                                    <li><a asp-area="" asp-controller="Order" asp-action="AllOrders">My Orders</a></li>
                                    <li><a asp-area="" asp-controller="Other" asp-action="AppFaq">FAQ & Support</a></li>
                                    @*<li><a asp-area="" asp-controller="Account" asp-action="AppFaq">Log In</a></li>*@
                                    @*<li class="active"><a href="#home">Home</a></li>
                                        <li><a href="#features">Features</a></li>
                                        <li><a href="#industry_verticals">Industry Verticals</a></li>
                                        <li><a href="#how_we_work">How we work</a></li>
                                        <li><a href="#price">Price</a></li>
                                        <li><a href="localhost">Blog</a></li>
                                        <li><a href="#contact">Contact Us</a></li>
                                        <li><a href="#faqs">FAQ</a></li>*@
                                    @await Html.PartialAsync("_LoginPartial")
                                </ul>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </header>
        <div id="main-body"> @RenderBody()</div>

    </div>
    <div id='loadingDiv'>
        <img src="~/images/loading2.gif" />
    </div>
    <environment include="Development,Production">


        <script src="~/cutoutwiz/js/core.min.js"></script>
        <script src="~/cutoutwiz/js/script.js"></script>

        @* <script src="~/lib/intl-tel-input/js/intlTelInput.  min.js"></script>*@

        <script src="~/lib/intl-tel-input/js/intlTelInput.min.js"></script>
        <script src="~/js/appScript.js"></script>
        <script src="~/lib/fakeLoader/fakeLoader.js"></script>
    </environment>
    @*<script type="text/javascript">
        $("#fakeLoader").fakeLoader();
    </script>*@
    @RenderSection("Scripts", required: false)
</body>
</html>

profilemanagement/Views/Shared/_GlobalSearch.cshtml
@*<div class="vd_menu-search">
    <form id="search-box" method="post" action="">
        <input type="text" name="search" class="vd_menu-search-text width-60" placeholder="Search">
        <div class="vd_menu-search-category">
            <span data-action="click-trigger"> <span class="separator"></span> <span class="text">Category</span> <span class="icon"> <i class="fa fa-caret-down"></i></span> </span>
            <div class="vd_mega-menu-content width-xs-2 center-xs-2 right-sm" data-action="click-target" style="display: none;">
                <div class="child-menu">
                    <div class="content-list content-menu content">
                        <ul class="list-wrapper">
                            <li>
                                <label>
                                    <input type="checkbox" value="all-files">
                                    <span>All Files</span>
                                </label>
                            </li>
                            <li>
                                <label>
                                    <input type="checkbox" value="photos">
                                    <span>Photos</span>
                                </label>
                            </li>
                            <li>
                                <label>
                                    <input type="checkbox" value="illustrations">
                                    <span>Illustrations</span>
                                </label>
                            </li>
                            <li>
                                <label>
                                    <input type="checkbox" value="video">
                                    <span>Video</span>
                                </label>
                            </li>
                            <li>
                                <label>
                                    <input type="checkbox" value="audio">
                                    <span>Audio</span>
                                </label>
                            </li>
                            <li>
                                <label>
                                    <input type="checkbox" value="flash">
                                    <span>Flash</span>
                                </label>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <span class="vd_menu-search-submit"><i class="fa fa-search"></i> </span>
    </form>
</div>*@

profilemanagement/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - Profile</title>
    <environment include="Development,Production">
        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Shadows+Into+Light%7CLibre+Franklin:200,300,400,600,700" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/cutoutwiz/css/style.css" />
        <link rel="stylesheet" href="~/css/thisSite.css" />
        <link rel="stylesheet" href="~/css/toastr.min.css"/>
       <link rel="stylesheet" href="~/lib/intl-tel-input/css/intlTelInput.css"/>
        <link rel="stylesheet" href="~/css/hover-min.css" />
        <link rel="stylesheet" href="~/lib/iziModal/css/iziModal.css"/>
        <link rel="stylesheet" href="~/css/fontawesome.min.css"/>
        <link rel="stylesheet" href="~/css/animate.css"/>

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/toastr.min.js"></script>
    </environment>
</head>
<body style="width:100%!important;overflow-x:hidden;">
    @RenderBody()
    <environment include="Development,Production">
        <script src="~/cutoutwiz/js/core.min.js"></script>

        <script src="~/cutoutwiz/js/script.js"></script>
        <script src="~/js/appScript.js"></script>
        <script src="~/lib/iziModal/js/iziModal.min.js"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

profilemanagement/Views/Shared/_Settings.cshtml
@using Microsoft.AspNetCore.Identity
@using ProfileManagement.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<div class="vd_mega-menu-content  width-xs-2  left-xs left-sm" data-action="click-target" style="display: none;">
    <div class="child-menu">
        <div class="content-list content-menu">
            <ul class="list-wrapper pd-lr-10">
                <li> <a href="@Url.Action("EditUser", "User")"> <div class="menu-icon"><i class=" fa fa-user"></i></div> <div class="menu-text">Udate Profile</div> </a> </li>
                <li class="line"></li>
                @*<li>
                    <a href="#">
                        <div class="menu-icon">
                            <i class=" fa fa-lock"></i>
                        </div> <div class="menu-text">Privacy</div>
                    </a>
                </li>*@
                <li> <a href="@Url.Action("UserInfo", "User")"> <div class="menu-icon"><i class=" fa fa-cogs"></i></div> <div class="menu-text">Settings</div> </a> </li>
                <li> <a href="#"> <div class="menu-icon"><i class="  fa fa-key"></i></div> <div class="menu-text">Do not disturb</div> </a> </li>
                @*<li><div class="menu-icon"><i class=" fa fa-sign-out"></i></div>  <div class="menu-text" onclick="javascript: app.Logout(this)">Sign Out</div></li>*@
                <li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                    <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm">
                        <div class="menu-icon left"><i class=" fa fa-sign-out"></i></div>  <div class="menu-text">
                            <button type="submit" style="width:100%; text-align:left; background-color:white;";>LogOut</button>
                        </div>
                    </form>
                    }
                </li>
            </ul>
        </div>
    </div>
</div>